baseURL = "https://nodematerial.github.io/samplesite/"
disablePathToLower = true
languageCode = "en-us"
title = "初めてのGoプログラミング"
theme = "docter"
publishDir = "docs"

[params]
  home = "初めてのGoプログラミング"
  subtitle = "こんにちは"

  author = "Kota Noda"
  author_url= "https://github.com/nodematerial"

  # Mention your hosting provider
  hosted_on = "Github"
  hosted_on_url= "#"

  # main sections
  # change the main section to set the directory where the top articles are sourced
  mainSections = ["post"]

  # brand color
  brand_color = "#5cc507"

[markup.goldmark.renderer]
  unsafe = true
